<?php
include("funcionFecha.php");
require('fpdf/fpdf.php');
$nombre = "JUAREZ GARCIA MANUEL";
$text1="BANCO REGIONAL, S.A.,";
$text2="INSTITUCIÓN DE BANCA MÚLTIPLE,";
$text3 = "BANREGIO GRUPO FINANCIERO,";
$text4 = "DEPARTAMENTO FIDUCIARIO";
$text5 = "PRESENTE";
$texto6 ='El suscrito '.$nombre.', por mi propio derecho y bajo protesta de decir verdad, declaro que NO CUENTO con Firma Electrónica Avanzada (FIEL), motivo por el cual, lógicamente, tampoco cuento con: (i) el Comprobante de Inscripción para la FIEL" (ii) el "Certificado de FIEL"; ni (iii) el número de serie de dicho "Certificado de FIEL".';
$texto7 = 'En consecuencia, libero a "Banco Regional de Monterrey", S.A., Institución de Banca Múltiple, Banregio Grupo Financiero, Departamento Fiduciario (en lo sucesivo "BanRegio") de toda y cualquier responsabilidad al respecto y me obligo a, que en caso de que en un futuro obtenga la FIEL proporcionaré a BanRegio, copia de los documentos antes relacionados, así como el número de serie del "Certificado de FIEL".';
$texto11 ='El suscrito '.$nombre.', por mi propio derecho y bajo protesta de decir verdad, declaro que NO ME ENCUENTRO dado de ALTA en el Registro Federal de Contribuyentes, motivo por el cual, lógicamente, tampoco cuento con: (i) con "Registro Federal de Contribuyentes con homoclave"; ni (ii) con "Cédula de Identificación Fiscal".';
$texto8 = "Atentamente,";
$texto12 = 'En consecuencia, libero a "Banco Regional de Monterrey", S.A., Institución de Banca Múltiple, Banregio Grupo Financiero, Departamento Fiduciario (en lo sucesivo "BanRegio") de toda y cualquier responsabilidad al respecto y me obligo a, que en caso de que en un futuro me dé de alta en el Registro Federal de Contribuyentes, proporcionaré a BanRegio, copia de los documentos antes relacionados.';
$texto9 = "___________________________";
$texto10 = "Por su propio derecho";
$texto8 = utf8_decode($texto8);
$text1 = utf8_decode($text1);
$text2 = utf8_decode($text2);
$text3 = utf8_decode($text3);
$text4 = utf8_decode($text4);
$text5 = utf8_decode($text5);
$texto6 = utf8_decode($texto6);
$texto7 = utf8_decode($texto7);
$pdf = new FPDF();
    $pdf->AddPage();
    $pdf->SetMargins(20, 20, 20);
    $pdf->SetFont('Arial','',12);
    $pdf->Cell(80);
    $pdf->Cell(40,10," Tuxtla Gutierrez, Chiapas, a ".$dia." de ".$nombreMes." de ". $anio);
    $pdf->Ln(25);
    $pdf->Cell(40,10,$text1);
    $pdf->Ln(6);
    $pdf->Cell(40,10,$text2);
    $pdf->Ln(6);
    $pdf->Cell(40,10,$text3);
    $pdf->Ln(6);
    $pdf->Cell(40,10,$text4);
    $pdf->Ln(6);
    $pdf->Cell(40,10,$text5);
    $pdf->Ln(20);
    $pdf->Cell(40,10,$text5);
    $pdf->Ln(20);
    $pdf->MultiCell(0,5,$texto6);
    $pdf->Ln(10);
    $pdf->MultiCell(0,5,$texto7);
    $pdf->Ln(25);
    $pdf->MultiCell(0,5,$texto8,0,'C');
    $pdf->Ln(25);
    $pdf->MultiCell(0,5,$texto9,0,'C');
    $pdf->Ln(2);
    $pdf->MultiCell(0,5,"SR. ".$nombre,0,'C');
    $pdf->AddPage();
    $pdf->SetMargins(20, 20, 20);
    $pdf->SetFont('Arial','',12);
    $pdf->Cell(80);
    $pdf->Cell(40,10," Tuxtla Gutierrez, Chiapas, a ".$dia." de ".$nombreMes." de ". $anio);
    $pdf->Ln(25);
    $pdf->Cell(40,10,$text1);
    $pdf->Ln(6);
    $pdf->Cell(40,10,$text2);
    $pdf->Ln(6);
    $pdf->Cell(40,10,$text3);
    $pdf->Ln(6);
    $pdf->Cell(40,10,$text4);
    $pdf->Ln(6);
    $pdf->Cell(40,10,$text5);
    $pdf->Ln(20);
    $pdf->Cell(40,10,$text5);
    $pdf->Ln(20);
    $pdf->MultiCell(0,5,utf8_decode($texto11));
    $pdf->Ln(10);
    $pdf->MultiCell(0,5,utf8_decode($texto12));
    $pdf->Ln(2);
    $pdf->MultiCell(0,5,"SR. ".$nombre,0,'C');
    $pdf->Output();
?>